# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(461, 300)
        MainWindow.setMinimumSize(QtCore.QSize(461, 300))
        MainWindow.setMaximumSize(QtCore.QSize(461, 300))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.newWord_widget = QtWidgets.QWidget(self.centralwidget)
        self.newWord_widget.setGeometry(QtCore.QRect(180, 0, 281, 301))
        self.newWord_widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.newWord_widget.setObjectName("newWord_widget")
        self.writeEnglish = QtWidgets.QLineEdit(self.newWord_widget)
        self.writeEnglish.setGeometry(QtCore.QRect(30, 90, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.writeEnglish.setFont(font)
        self.writeEnglish.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"border: 2px solid rgb(197, 197, 255);\n"
"border-radius: 10px;")
        self.writeEnglish.setInputMethodHints(QtCore.Qt.ImhNone)
        self.writeEnglish.setInputMask("")
        self.writeEnglish.setAlignment(QtCore.Qt.AlignCenter)
        self.writeEnglish.setClearButtonEnabled(False)
        self.writeEnglish.setObjectName("writeEnglish")
        self.writeRussian = QtWidgets.QLineEdit(self.newWord_widget)
        self.writeRussian.setGeometry(QtCore.QRect(30, 160, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.writeRussian.setFont(font)
        self.writeRussian.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"border: 2px solid rgb(197, 197, 255);\n"
"border-radius: 10px;")
        self.writeRussian.setAlignment(QtCore.Qt.AlignCenter)
        self.writeRussian.setObjectName("writeRussian")
        self.en_label = QtWidgets.QLabel(self.newWord_widget)
        self.en_label.setGeometry(QtCore.QRect(30, 70, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.en_label.setFont(font)
        self.en_label.setStyleSheet("color: rgb(91, 91, 91);")
        self.en_label.setAlignment(QtCore.Qt.AlignCenter)
        self.en_label.setObjectName("en_label")
        self.ru_label = QtWidgets.QLabel(self.newWord_widget)
        self.ru_label.setGeometry(QtCore.QRect(30, 140, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.ru_label.setFont(font)
        self.ru_label.setStyleSheet("color: rgb(91, 91, 91);")
        self.ru_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ru_label.setObjectName("ru_label")
        self.newWord_button = QtWidgets.QPushButton(self.newWord_widget)
        self.newWord_button.setGeometry(QtCore.QRect(90, 220, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.newWord_button.setFont(font)
        self.newWord_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(66, 75, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(197, 197, 255);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 0, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(85, 0, 255);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(85, 0, 255);\n"
"}")
        self.newWord_button.setObjectName("newWord_button")
        self.buttons_widget = QtWidgets.QWidget(self.centralwidget)
        self.buttons_widget.setGeometry(QtCore.QRect(0, 0, 181, 301))
        self.buttons_widget.setStyleSheet("background-color: rgb(151, 147, 255);")
        self.buttons_widget.setObjectName("buttons_widget")
        self.newWord_btn = QtWidgets.QPushButton(self.buttons_widget)
        self.newWord_btn.setGeometry(QtCore.QRect(20, 70, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.newWord_btn.setFont(font)
        self.newWord_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 3px inset rgb(66, 75, 255);\n"
"    border-radius: 10px;\n"
"    color: rgb(91, 91, 91);\n"
"    position: absolute;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(199, 253, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(139, 141, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.newWord_btn.setObjectName("newWord_btn")
        self.searchWord_btn = QtWidgets.QPushButton(self.buttons_widget)
        self.searchWord_btn.setGeometry(QtCore.QRect(20, 140, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.searchWord_btn.setFont(font)
        self.searchWord_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 3px inset rgb(66, 75, 255);\n"
"    border-radius: 10px;\n"
"    color: rgb(91, 91, 91);\n"
"    position: absolute;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(199, 253, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(139, 141, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.searchWord_btn.setObjectName("searchWord_btn")
        self.translateMenu_btn = QtWidgets.QPushButton(self.buttons_widget)
        self.translateMenu_btn.setGeometry(QtCore.QRect(20, 210, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.translateMenu_btn.setFont(font)
        self.translateMenu_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 3px inset rgb(66, 75, 255);\n"
"    border-radius: 10px;\n"
"    color: rgb(91, 91, 91);\n"
"    position: absolute;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(199, 253, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(139, 141, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.translateMenu_btn.setObjectName("translateMenu_btn")
        self.searchWord_widget = QtWidgets.QWidget(self.centralwidget)
        self.searchWord_widget.setEnabled(True)
        self.searchWord_widget.setGeometry(QtCore.QRect(180, 0, 281, 301))
        self.searchWord_widget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.searchWord_widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.searchWord_widget.setObjectName("searchWord_widget")
        self.wordList = QtWidgets.QTableWidget(self.searchWord_widget)
        self.wordList.setGeometry(QtCore.QRect(20, 130, 241, 151))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.wordList.setFont(font)
        self.wordList.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.wordList.setAutoFillBackground(False)
        self.wordList.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"border-top: 1px solid rgb(151, 147, 255);\n"
"color: rgb(91, 91, 91);")
        self.wordList.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.wordList.setObjectName("wordList")
        self.wordList.setColumnCount(2)
        self.wordList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.wordList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.wordList.setHorizontalHeaderItem(1, item)
        self.wordList.horizontalHeader().setStretchLastSection(True)
        self.wordList.verticalHeader().setStretchLastSection(False)
        self.en_check = QtWidgets.QRadioButton(self.searchWord_widget)
        self.en_check.setGeometry(QtCore.QRect(20, 20, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.en_check.setFont(font)
        self.en_check.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.en_check.setStyleSheet("QRadioButton {\n"
"color: rgb(91, 91, 91);\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"width: 11px;\n"
"height: 11px;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked{ \n"
"border: 1px solid; \n"
"border-color: rgb(132,132,132);\n"
"border-radius: 5px;\n"
"background-color: white; \n"
"width: 11px; \n"
"height: 11px; \n"
"}\n"
"\n"
"QRadioButton::indicator::checked{ \n"
"border: 3px solid; \n"
"border-color: white;\n"
"border-radius: 6px;\n"
"background-color: rgb(0,116,188); \n"
"width: 7px; \n"
"height: 7px; \n"
"}")
        self.en_check.setObjectName("en_check")
        self.ru_check = QtWidgets.QRadioButton(self.searchWord_widget)
        self.ru_check.setGeometry(QtCore.QRect(150, 20, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.ru_check.setFont(font)
        self.ru_check.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ru_check.setAutoFillBackground(False)
        self.ru_check.setStyleSheet("QRadioButton {\n"
"color: rgb(91, 91, 91);\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"width: 11px;\n"
"height: 11px;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked{ \n"
"border: 1px solid; \n"
"border-color: rgb(132,132,132);\n"
"border-radius: 5px;\n"
"background-color: white; \n"
"width: 11px; \n"
"height: 11px; \n"
"}\n"
"\n"
"QRadioButton::indicator::checked{ \n"
"border: 3px solid; \n"
"border-color: white;\n"
"border-radius: 6px;\n"
"background-color: rgb(0,116,188); \n"
"width: 8px; \n"
"height: 8px; \n"
"}")
        self.ru_check.setCheckable(True)
        self.ru_check.setChecked(True)
        self.ru_check.setObjectName("ru_check")
        self.search_line = QtWidgets.QLineEdit(self.searchWord_widget)
        self.search_line.setGeometry(QtCore.QRect(20, 50, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.search_line.setFont(font)
        self.search_line.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"border: 2px solid rgb(197, 197, 255);\n"
"border-radius: 5px;")
        self.search_line.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.search_line.setObjectName("search_line")
        self.search_btn = QtWidgets.QPushButton(self.searchWord_widget)
        self.search_btn.setGeometry(QtCore.QRect(200, 50, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.search_btn.setFont(font)
        self.search_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(66, 75, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(197, 197, 255);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 0, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(85, 0, 255);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(85, 0, 255);\n"
"}")
        self.search_btn.setObjectName("search_btn")
        self.allWords_btn = QtWidgets.QPushButton(self.searchWord_widget)
        self.allWords_btn.setGeometry(QtCore.QRect(100, 90, 81, 31))
        self.allWords_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(66, 75, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(197, 197, 255);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 0, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(85, 0, 255);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(85, 0, 255);\n"
"}")
        self.allWords_btn.setObjectName("allWords_btn")
        self.translate_widget = QtWidgets.QWidget(self.centralwidget)
        self.translate_widget.setGeometry(QtCore.QRect(180, 0, 281, 301))
        self.translate_widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.translate_widget.setObjectName("translate_widget")
        self.trans_to_ru = QtWidgets.QRadioButton(self.translate_widget)
        self.trans_to_ru.setGeometry(QtCore.QRect(30, 120, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.trans_to_ru.setFont(font)
        self.trans_to_ru.setStyleSheet("QRadioButton {\n"
"color: rgb(91, 91, 91);\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"width: 11px;\n"
"height: 11px;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked{ \n"
"border: 1px solid; \n"
"border-color: rgb(132,132,132);\n"
"border-radius: 5px;\n"
"background-color: white; \n"
"width: 11px; \n"
"height: 11px; \n"
"}\n"
"\n"
"QRadioButton::indicator::checked{ \n"
"border: 3px solid; \n"
"border-color: white;\n"
"border-radius: 6px;\n"
"background-color: rgb(0,116,188); \n"
"width: 8px; \n"
"height: 8px; \n"
"}")
        self.trans_to_ru.setChecked(True)
        self.trans_to_ru.setObjectName("trans_to_ru")
        self.trans_to_en = QtWidgets.QRadioButton(self.translate_widget)
        self.trans_to_en.setGeometry(QtCore.QRect(146, 120, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.trans_to_en.setFont(font)
        self.trans_to_en.setStyleSheet("QRadioButton {\n"
"color: rgb(91, 91, 91);\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"width: 11px;\n"
"height: 11px;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked{ \n"
"border: 1px solid; \n"
"border-color: rgb(132,132,132);\n"
"border-radius: 5px;\n"
"background-color: white; \n"
"width: 11px; \n"
"height: 11px; \n"
"}\n"
"\n"
"QRadioButton::indicator::checked{ \n"
"border: 3px solid; \n"
"border-color: white;\n"
"border-radius: 6px;\n"
"background-color: rgb(0,116,188); \n"
"width: 8px; \n"
"height: 8px; \n"
"}")
        self.trans_to_en.setObjectName("trans_to_en")
        self.translate_btn = QtWidgets.QPushButton(self.translate_widget)
        self.translate_btn.setGeometry(QtCore.QRect(90, 150, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.translate_btn.setFont(font)
        self.translate_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(66, 75, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(197, 197, 255);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 0, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(85, 0, 255);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(85, 0, 255);\n"
"}")
        self.translate_btn.setObjectName("translate_btn")
        self.result_label = QtWidgets.QLabel(self.translate_widget)
        self.result_label.setGeometry(QtCore.QRect(40, 200, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.result_label.setFont(font)
        self.result_label.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"border: 2px solid rgb(197, 197, 255);\n"
"border-radius: 5px;\n"
"color: rgb(91, 91, 91);")
        self.result_label.setAlignment(QtCore.Qt.AlignCenter)
        self.result_label.setObjectName("result_label")
        self.label = QtWidgets.QLabel(self.translate_widget)
        self.label.setGeometry(QtCore.QRect(90, 50, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(91, 91, 91);\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.translate_widget)
        self.lineEdit.setGeometry(QtCore.QRect(40, 79, 201, 31))
        self.lineEdit.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"border: 2px solid rgb(197, 197, 255);\n"
"border-radius: 5px;\n"
"color: rgb(91, 91, 91);")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.tts_btn = QtWidgets.QPushButton(self.translate_widget)
        self.tts_btn.setGeometry(QtCore.QRect(210, 170, 23, 23))
        self.tts_btn.setStyleSheet("QPushButton {\n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"}")
        self.tts_btn.setText("")
        self.tts_btn.setObjectName("tts_btn")
        self.buttons_widget.raise_()
        self.newWord_widget.raise_()
        self.searchWord_widget.raise_()
        self.translate_widget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Lang-Guru"))
        self.en_label.setText(_translate("MainWindow", "Английский язык"))
        self.ru_label.setText(_translate("MainWindow", "Русский язык"))
        self.newWord_button.setText(_translate("MainWindow", "Добавить"))
        self.newWord_btn.setText(_translate("MainWindow", "Добавить слово"))
        self.searchWord_btn.setText(_translate("MainWindow", "Найти слово"))
        self.translateMenu_btn.setText(_translate("MainWindow", "Переводчик"))
        item = self.wordList.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Русский"))
        item = self.wordList.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Английский"))
        self.en_check.setText(_translate("MainWindow", "Английский язык"))
        self.ru_check.setText(_translate("MainWindow", "Русский язык"))
        self.search_btn.setText(_translate("MainWindow", "Найти"))
        self.allWords_btn.setText(_translate("MainWindow", "Все слова"))
        self.trans_to_ru.setText(_translate("MainWindow", "На русский"))
        self.trans_to_en.setText(_translate("MainWindow", "На английский"))
        self.translate_btn.setText(_translate("MainWindow", "Перевести"))
        self.result_label.setText(_translate("MainWindow", "Результат"))
        self.label.setText(_translate("MainWindow", "Введите слово"))
